"""remove many-to-many from user gardens

Revision ID: 153113bbf974
Revises: 0e3dd638325a
Create Date: 2026-02-18 12:52:40.298126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153113bbf974'
down_revision: Union[str, Sequence[str], None] = '0e3dd638325a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_gardens')
    op.add_column('gardens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gardens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gardens', type_='foreignkey')
    op.drop_column('gardens', 'user_id')
    op.create_table('user_gardens',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('garden_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], name=op.f('user_gardens_garden_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_gardens_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'garden_id', name=op.f('user_gardens_pkey'))
    )
    # ### end Alembic commands ###
