"""add gardenPlantImage table to db

Revision ID: 20dc2e87fcdc
Revises: 7f0a2a9a17de
Create Date: 2026-04-10 11:00:08.704351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20dc2e87fcdc'
down_revision: Union[str, Sequence[str], None] = '7f0a2a9a17de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_plant_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_name', sa.String(), nullable=False),
    sa.Column('garden_plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garden_plant_id'], ['garden_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden_plant_images')
    # ### end Alembic commands ###
