"""fix plant section relationship

Revision ID: 2a83cef79fbf
Revises: 71ca9921cbb1
Create Date: 2026-02-21 20:50:25.831990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a83cef79fbf'
down_revision: Union[str, Sequence[str], None] = '71ca9921cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_plants', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('section_plants', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_plants', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('section_plants', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
