"""add plant and garden tables

Revision ID: 2e2c8c65cbc8
Revises: 23eb27e89473
Create Date: 2026-02-11 13:24:43.005943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2c8c65cbc8'
down_revision: Union[str, Sequence[str], None] = '23eb27e89473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_water_frequency', sa.Integer(), nullable=True),
    sa.Column('max_water_frequency', sa.Integer(), nullable=True),
    sa.Column('soil_moisture', sa.Enum('dry', 'moderate', 'wet', name='moistureenum'), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('soil_type', sa.Enum('loamy', 'sandy', 'peaty', name='soilenum'), nullable=True),
    sa.Column('min_soil_ph', sa.Float(), nullable=True),
    sa.Column('max_soil_ph', sa.Float(), nullable=True),
    sa.Column('fertilizer_frequency', sa.Integer(), nullable=True),
    sa.Column('fertilizer_nitrogen', sa.Integer(), nullable=True),
    sa.Column('fertilizer_phosphorus', sa.Integer(), nullable=True),
    sa.Column('fertilizer_potassium', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edible_fruit', sa.Boolean(), nullable=True),
    sa.Column('edible_leaves', sa.Boolean(), nullable=True),
    sa.Column('edible_flowers', sa.Boolean(), nullable=True),
    sa.Column('edible_roots', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('light_type', sa.Enum('direct_light', 'bright_indirect_light', 'shade', name='lightenum'), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.Column('min_humidity', sa.Float(), nullable=True),
    sa.Column('max_humidity', sa.Float(), nullable=True),
    sa.Column('min_usda_zone', sa.String(), nullable=True),
    sa.Column('max_usda_zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annual', sa.Boolean(), nullable=True),
    sa.Column('biennial', sa.Boolean(), nullable=True),
    sa.Column('perennial', sa.Boolean(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('max_width', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Enum('fast', 'moderate', 'slow', name='growthrateenum'), nullable=True),
    sa.Column('min_days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('max_days_to_harvest', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spacing', sa.Float(), nullable=True),
    sa.Column('seed_depth', sa.Float(), nullable=True),
    sa.Column('direct_sow', sa.Boolean(), nullable=True),
    sa.Column('transplant', sa.Boolean(), nullable=True),
    sa.Column('propagation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toxicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toxic_to_cats', sa.Boolean(), nullable=True),
    sa.Column('toxic_to_dogs', sa.Boolean(), nullable=True),
    sa.Column('toxic_to_humans', sa.Boolean(), nullable=True),
    sa.Column('toxicity', sa.Enum('non_toxic', 'mildly_toxic', 'moderately_toxic', 'highly_toxic', name='toxicityenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=50), nullable=True),
    sa.Column('scientific_name', sa.String(length=50), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('order', sa.String(length=50), nullable=True),
    sa.Column('class_', sa.String(length=50), nullable=True),
    sa.Column('phylum', sa.String(length=50), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('toxicity_id', sa.Integer(), nullable=True),
    sa.Column('edibility_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('care_requirements_id', sa.Integer(), nullable=True),
    sa.Column('growth_id', sa.Integer(), nullable=True),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['care_requirements_id'], ['care_requirements.id'], ),
    sa.ForeignKeyConstraint(['edibility_id'], ['edibility.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['growth_id'], ['growth.id'], ),
    sa.ForeignKeyConstraint(['planting_id'], ['planting.id'], ),
    sa.ForeignKeyConstraint(['toxicity_id'], ['toxicity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_gardens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'garden_id')
    )
    op.create_table('garden_plants',
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('garden_id', 'plant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden_plants')
    op.drop_table('user_gardens')
    op.drop_table('plants')
    op.drop_table('toxicity')
    op.drop_table('planting')
    op.drop_table('growth')
    op.drop_table('gardens')
    op.drop_table('environment')
    op.drop_table('edibility')
    op.drop_table('care_requirements')
    # ### end Alembic commands ###
