"""add description to garden

Revision ID: 3f8ef5aef00d
Revises: bc2ff8057edd
Create Date: 2026-02-12 15:51:14.520398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8ef5aef00d'
down_revision: Union[str, Sequence[str], None] = 'bc2ff8057edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('description', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'description')
    # ### end Alembic commands ###
