"""Plants belong to gardens, gardens can optionally have sections

Revision ID: 649867758e41
Revises: a264fcef6f04
Create Date: 2026-02-27 11:00:33.784407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649867758e41'
down_revision: Union[str, Sequence[str], None] = 'a264fcef6f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_plants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_plants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('section_plants_plant_id_fkey')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('section_plants_section_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('section_plants_pkey'))
    )
    # ### end Alembic commands ###
