"""add min plant width and height to Growth table

Revision ID: 7f0a2a9a17de
Revises: e949b60027bc
Create Date: 2026-04-07 13:29:59.505761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0a2a9a17de'
down_revision: Union[str, Sequence[str], None] = 'e949b60027bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('growth', sa.Column('min_height', sa.Float(), nullable=True))
    op.add_column('growth', sa.Column('min_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth', 'min_width')
    op.drop_column('growth', 'min_height')
    # ### end Alembic commands ###
