"""made garden_id not nullable in section table

Revision ID: 91b48cb6d9e3
Revises: 7f99651e0655
Create Date: 2026-03-16 16:22:09.667348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b48cb6d9e3'
down_revision: Union[str, Sequence[str], None] = '7f99651e0655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'garden_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'garden_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
