"""add cascade delete for gardenplants and sections

Revision ID: a1b158382c41
Revises: 203bf1c04073
Create Date: 2026-03-03 13:15:23.896390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b158382c41'
down_revision: Union[str, Sequence[str], None] = '203bf1c04073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('garden_plants_plant_id_fkey'), 'garden_plants', type_='foreignkey')
    op.drop_constraint(op.f('garden_plants_garden_id_fkey'), 'garden_plants', type_='foreignkey')
    op.create_foreign_key(None, 'garden_plants', 'plants', ['plant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'garden_plants', 'gardens', ['garden_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sections_garden_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'gardens', ['garden_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_garden_id_fkey'), 'sections', 'gardens', ['garden_id'], ['id'])
    op.drop_constraint(None, 'garden_plants', type_='foreignkey')
    op.drop_constraint(None, 'garden_plants', type_='foreignkey')
    op.create_foreign_key(op.f('garden_plants_garden_id_fkey'), 'garden_plants', 'gardens', ['garden_id'], ['id'])
    op.create_foreign_key(op.f('garden_plants_plant_id_fkey'), 'garden_plants', 'plants', ['plant_id'], ['id'])
    # ### end Alembic commands ###
