"""Plant table correctly linked with SectionPlant

Revision ID: a264fcef6f04
Revises: dad2eeb478d1
Create Date: 2026-02-22 20:12:06.307932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a264fcef6f04'
down_revision: Union[str, Sequence[str], None] = 'dad2eeb478d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
