"""add cascade to sections and garden plants4

Revision ID: adb3ce94710c
Revises: 9dd7833997ea
Create Date: 2026-03-16 16:48:47.765361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb3ce94710c'
down_revision: Union[str, Sequence[str], None] = '9dd7833997ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('garden_plants_section_id_fkey'), 'garden_plants', type_='foreignkey')
    op.create_foreign_key(None, 'garden_plants', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garden_plants', type_='foreignkey')
    op.create_foreign_key(op.f('garden_plants_section_id_fkey'), 'garden_plants', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
