"""add order to section tabs

Revision ID: d4dae13830b8
Revises: 2d8a8fd0ed06
Create Date: 2026-03-19 12:12:52.730339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dae13830b8'
down_revision: Union[str, Sequence[str], None] = '2d8a8fd0ed06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'order')
    # ### end Alembic commands ###
