"""add cascade to garden_tags

Revision ID: d8e57be2e723
Revises: 153113bbf974
Create Date: 2026-02-19 20:31:44.013411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e57be2e723'
down_revision: Union[str, Sequence[str], None] = '153113bbf974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('garden_tags_garden_id_fkey'), 'garden_tags', type_='foreignkey')
    op.drop_constraint(op.f('garden_tags_tag_id_fkey'), 'garden_tags', type_='foreignkey')
    op.create_foreign_key(None, 'garden_tags', 'gardens', ['garden_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'garden_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garden_tags', type_='foreignkey')
    op.drop_constraint(None, 'garden_tags', type_='foreignkey')
    op.create_foreign_key(op.f('garden_tags_tag_id_fkey'), 'garden_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('garden_tags_garden_id_fkey'), 'garden_tags', 'gardens', ['garden_id'], ['id'])
    # ### end Alembic commands ###
