"""fix section sectionPlant relationship back populates

Revision ID: dad2eeb478d1
Revises: 2a83cef79fbf
Create Date: 2026-02-22 20:09:42.282381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad2eeb478d1'
down_revision: Union[str, Sequence[str], None] = '2a83cef79fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
