"""add sections to gardens

Revision ID: e42560ced174
Revises: 3f8ef5aef00d
Create Date: 2026-02-12 16:28:21.639847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42560ced174'
down_revision: Union[str, Sequence[str], None] = '3f8ef5aef00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_sections',
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('garden_id', 'section_id')
    )
    op.create_table('section_plants',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'plant_id')
    )
    op.drop_table('garden_plants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_plants',
    sa.Column('garden_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], name=op.f('garden_plants_garden_id_fkey')),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('garden_plants_plant_id_fkey')),
    sa.PrimaryKeyConstraint('garden_id', 'plant_id', name=op.f('garden_plants_pkey'))
    )
    op.drop_table('section_plants')
    op.drop_table('garden_sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
